services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10

  data:
    build:
      context: .
      dockerfile: Data/Dockerfile
    container_name: data
    working_dir: /app
    ports:
      - "9104:9104"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
      Seq__ServerUrl: "http://seq:80"
    depends_on:
      postgres_db:
        condition: service_healthy
      seq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9104/metrics || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: admin
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: "QFVV75aOlK1ggpHQqJ+H5BFA2TXkje+YQx0jT3rhLQmjn/S2r4sjyJg0q/YJr44KODYePvta2TS3fx2tCaC4uPoB/FJR2YimfWuW9Szgn5cU" #PWD: 123
    ports:
      - "5341:80"
    volumes:
      - seqdata:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheusdata:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafanadata:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  controllers:
    build:
      context: .
      dockerfile: Controllers/Dockerfile
    container_name: controllers
    working_dir: /app
    ports:
      - "5001:5000"
      - "9101:9101"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
      Seq__ServerUrl: "http://seq:80"
    depends_on:
      postgres_db:
        condition: service_healthy
      seq:
        condition: service_healthy

  relay:
    build:
      context: .
      dockerfile: Relay/Dockerfile
    working_dir: /app
    expose:
      - "9102"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
      Seq__ServerUrl: "http://seq:80"
    depends_on:
      postgres_db:
        condition: service_healthy
      data:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_healthy
    deploy:
      replicas: 3

  worker-node:
    build:
      context: .
      dockerfile: Worker_Node/Dockerfile
    working_dir: /app
    expose:
      - "9102"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
      Seq__ServerUrl: "http://seq:80"
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_healthy
    deploy:
        replicas: 3
volumes:
  pgdata:
  seqdata:
  prometheusdata:
  grafanadata: