apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: data
          image: ghcr.io/hkeys00/data:v1.0.1
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgresql-sfs-0.postgresql-svc.default.svc.cluster.local;Port=5432;Database=postgres;Username=postgres;Password=mypassword"
      restartPolicy: Never
  backoffLimit: 4
