apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app: rabbitmq-a
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: rbtmq-amqp-port
    - name: management
      protocol: TCP
      port: 15672
      targetPort: rbtmq-mgmt-port