apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  selector:
    app: postgresql-a
  ports:
    - name: postgres
      protocol: TCP
      port: 80
      targetPort: postgresql-port